# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  sln: './src/minsk.sln'
  tests: './src/Minsk.Tests/Minsk.Tests.csproj'

steps:
- script: dotnet build --configuration $(buildConfiguration) $(sln)
  displayName: 'dotnet build $(buildConfiguration)'
- script: dotnet test $(tests) --logger "xunit;LogFileName=TestResults.xml"
  displayName: 'dotnet test'
- task: PublishTestResults@2
  displayName: 'publish test results to azure pipelines'
  inputs:
    testResultsFormat: 'xUnit'
    testResultsFiles: '**/TestResults.xml'
  condition: always()